# Generated by Django 4.2.3 on 2023-07-05 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finkargo_app', '0003_alter_usertokens_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('cellphone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('begin_date', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='name',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='UserTokens',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='registered_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_user', to='finkargo_app.userregistration'),
        ),
    ]
