# Generated by Django 4.2.3 on 2023-07-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finkargo_app', '0004_userdata_usertoken_remove_userregistration_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='registered_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='finkargo_app.userregistration'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='registered_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='finkargo_app.userregistration'),
        ),
    ]
