# Generated by Django 4.2.3 on 2023-07-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finkargo_app', '0005_userdata_registered_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='begin_date',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
