# Generated by Django 4.2.3 on 2023-07-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finkargo_app', '0006_remove_userregistration_begin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='create_date',
            field=models.CharField(null=True),
        ),
    ]
