# Generated by Django 4.2.3 on 2023-07-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finkargo_app', '0007_alter_userregistration_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertoken',
            name='begin_date',
        ),
        migrations.AddField(
            model_name='usertoken',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
